version: "3"
services:
  api:
    image: sbgtechtest/api:2.0.0
    ports:
      - "8888-8890:8888-8890"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
